import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    appName: "KisanSaathi",
    tagline: "Do one thing, KisanSaathi does the rest",
    punjabiTagline: "ਇੱਕ ਕੰਮ ਕਰੋ, ਬਾਕੀ ਸਭ ਕਿਸਾਨ ਸਾਥੀ ਕਰੇਗਾ",
    statBar: "10% farmers have insurance · ₹1500Cr lost to crop damage · 72hr claim window most farmers miss",
    startInLanguage: "Start in Punjabi",
    selectLanguage: "Choose Language",
    next: "Next",
    back: "Back",
    submit: "Submit",
    complete: "Complete Setup",
    loading: "Loading...",
    
    // Onboarding
    onboardTitle: "Farmer Onboarding",
    step: "Step",
    nameLabel: "What is your name?",
    namePlaceholder: "Enter your full name",
    districtLabel: "Which district is your farm in?",
    districtSelect: "Select District",
    landLabel: "What is your land size (in Acres)?",
    landPlaceholder: "Acres",
    landHectares: "Equivalent in Hectares",
    primaryCropLabel: "What is your primary crop?",
    secondaryCropLabel: "What is your secondary crop? (Optional)",
    secondaryCropNone: "None",
    cropSelect: "Select Crop",
    insuranceLabel: "Do you currently have crop insurance?",
    insuranceYes: "Yes, I have insurance",
    insuranceNo: "No, I do not have",
    insuranceUnsure: "Not sure",
    aadhaarLabel: "Aadhaar Card (Last 4 digits for claim pre-fill)",
    aadhaarPlaceholder: "1234",
    phoneLabel: "Phone Number (For WhatsApp reminders)",
    phonePlaceholder: "10-digit mobile number",

    // Dashboard
    dashboardTitle: "KisanSaathi Dashboard",
    riskForecast: "Risk Forecast",
    overallRisk: "Overall Risk",
    riskScore: "Risk Score",
    topThreats: "Top Threats",
    sowingAdvice: "Sowing & Farming Advice",
    recommendedInsurance: "Recommended Policy",
    activePolicy: "Active Policy Coverage",
    enrolledStatus: "Enrolled & Active",
    premiumPaid: "Premium Paid",
    sumInsured: "Sum Insured",
    changePolicy: "Change Policy",
    activeClaims: "Active Claims Status",
    noClaims: "No active claims filed yet.",
    seeAllOptions: "See all options",
    followUp: "Follow Up",
    remaining: "remaining",
    days: "d",
    hours: "h",
    minutes: "m",
    seconds: "s",
    weatherForecastTitle: "14-Day Weather Forecast",
    tempMax: "Max Temp (°C)",
    precip: "Rain (mm)",

    // Voice Chat
    voiceAgent: "KisanSaathi Voice Companion",
    speakNow: "Speak now...",
    tapMic: "Tap mic to speak",
    listening: "Listening...",
    processing: "Processing...",
    voiceSupportError: "Speech recognition not supported in this browser. Use typing fallback.",
    typePlaceholder: "Type your query here in your language...",
    startClaimButton: "Start Filing Claim 🌾",
    seePoliciesButton: "See Policy Options 📋",

    // Policy Advisor
    policyAdvisorTitle: "Crop Insurance Advisor",
    premium: "Premium",
    coverage: "Coverage",
    claimSpeed: "Claim Settlement",
    bestFor: "Best For",
    applyNow: "Enroll Now",
    howToApply: "How to Apply",
    recommendedBadge: "Best for You",
    estPremium: "Estimated Premium",
    estCoverage: "Estimated Coverage",
    acreVal: "per acre value",

    // Claim Filing
    fileClaimTitle: "File a Crop Damage Claim",
    claimStep1: "Damage Report",
    claimStep2: "Photo Verification",
    claimStep3: "Farmer Details",
    claimStep4: "Review & Submit",
    damageCropLabel: "Which crop is damaged?",
    damageDateLabel: "When did the damage occur?",
    damageTypeLabel: "What type of damage is it?",
    acresAffectedLabel: "How many acres are affected?",
    photoLabel: "Upload Photo of Damage (Optional)",
    photoAnalyzing: "Gemini AI is analyzing the damage photo...",
    photoSuccess: "Analysis complete!",
    bankAccountLabel: "Bank Account Number",
    ifscLabel: "IFSC Code",
    insPolicyLabel: "Select Your Insurance Policy",
    reviewHeading: "Verify Information Before Submission",
    fileClaimBtn: "File Claim Now",
    claimSuccessTitle: "Claim Filed Successfully!",
    claimSuccessMsg: "Your claim has been registered. We will remind you if there is no update within 48 hours.",
    claimIdText: "Claim ID",
    deadlineText: "72-Hour Response Deadline",

    // Claim Tracker
    trackerTitle: "Claim Tracker",
    claimId: "Claim ID",
    dateFiled: "Filed on",
    statusFiled: "Filed",
    statusVerified: "Verified",
    statusUnderReview: "Under Review",
    statusApproved: "Approved",
    statusPaid: "Compensation Disbursed",
    viewDetails: "View Details",
    hideDetails: "Hide Details",

    // Enrollment Wizard
    enrollTitle: "Digital Insurance Enrollment",
    enrollStep1: "Scan Aadhaar Card",
    enrollStep2: "Scan Land Records",
    enrollStep3: "Policy Recommendation",
    enrollStep4: "Generate & Download",
    scanAadhaarLabel: "Aadhaar Photo",
    scanLandLabel: "Land Document Photo",
    scanAadhaarDesc: "Please upload a clear photo of your Aadhaar card. The AI will extract your details automatically.",
    scanLandDesc: "Please upload a clear photo of your Land Record / Jamabandi document.",
    looksGood: "Does this look correct?",
    confirmBtn: "Confirm & Proceed",
    retakeBtn: "Retake / Re-upload",
    recommendationTitle: "Personalized Policy Selection",
    generatePDFBtn: "Generate Application PDF",
    downloadPDFBtn: "Download Application PDF",
    whatsappShareBtn: "Share via WhatsApp",
    successAppTitle: "Application Generated!",
    successAppMsg: "Your policy application PDF has been successfully generated. Please print and submit it at the nearest Common Service Centre (CSC) or bank agent.",
    mismatchWarning: "Warning: Extracted farmer name does not match Aadhaar name! Please double check.",
    extractedDetails: "AI Extracted Information",
    confidenceLabel: "AI Confidence Level",
    dobLabel: "Date of Birth",
    acresLabel: "Total Acres",
    landTypeLabel: "Land Category"
  },
  pa: {
    appName: "ਕਿਸਾਨਸਾਥੀ",
    tagline: "ਇੱਕ ਕੰਮ ਕਰੋ, ਬਾਕੀ ਸਭ ਕਿਸਾਨਸਾਥੀ ਕਰੇਗਾ",
    punjabiTagline: "ਇੱਕ ਕੰਮ ਕਰੋ, ਬਾਕੀ ਸਭ ਕਿਸਾਨ ਸਾਥੀ ਕਰੇਗਾ",
    statBar: "10% ਕਿਸਾਨਾਂ ਕੋਲ ਬੀਮਾ ਹੈ · ₹1500 ਕਰੋੜ ਫਸਲ ਦੇ ਨੁਕਸਾਨ ਕਾਰਨ ਬਰਬਾਦ · 72 ਘੰਟੇ ਦਾ ਦਾਅਵਾ ਸਮਾਂ ਜੋ ਬਹੁਤੇ ਕਿਸਾਨ ਖੁੰਝ ਜਾਂਦੇ ਹਨ",
    startInLanguage: "ਪੰਜਾਬੀ ਵਿੱਚ ਸ਼ੁਰੂ ਕਰੋ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    next: "ਅੱਗੇ",
    back: "ਪਿੱਛੇ",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    complete: "ਸੈੱਟਅੱਪ ਪੂਰਾ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",

    // Onboarding
    onboardTitle: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ ਸੈੱਟਅੱਪ",
    step: "ਕਦਮ",
    nameLabel: "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ?",
    namePlaceholder: "ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    districtLabel: "ਤੁਹਾਡਾ ਖੇਤ ਕਿਸ ਜ਼ਿਲ੍ਹੇ ਵਿੱਚ ਹੈ?",
    districtSelect: "ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
    landLabel: "ਤੁਹਾਡੀ ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ ਕਿੰਨਾ ਹੈ (ਏਕੜ ਵਿੱਚ)?",
    landPlaceholder: "ਏਕੜ",
    landHectares: "ਹੈਕਟੇਅਰ ਵਿੱਚ ਬਰਾਬਰ",
    primaryCropLabel: "ਤੁਹਾਡੀ ਮੁੱਖ ਫਸਲ ਕਿਹੜੀ ਹੈ?",
    secondaryCropLabel: "ਤੁਹਾਡੀ ਦੂਜੀ ਫਸਲ ਕਿਹੜੀ ਹੈ? (ਵਿਕਲਪਿਕ)",
    secondaryCropNone: "ਕੋਈ ਨਹੀਂ",
    cropSelect: "ਫਸਲ ਚੁਣੋ",
    insuranceLabel: "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਇਸ ਸਮੇਂ ਫਸਲ ਬੀਮਾ ਹੈ?",
    insuranceYes: "ਹਾਂ, ਮੇਰੇ ਕੋਲ ਬੀਮਾ ਹੈ",
    insuranceNo: "ਨਹੀਂ, ਮੇਰੇ ਕੋਲ ਨਹੀਂ ਹੈ",
    insuranceUnsure: "ਪਤਾ ਨਹੀਂ",
    aadhaarLabel: "ਆਧਾਰ ਕਾਰਡ (ਆਖਰੀ 4 ਅੰਕ - ਦਾਅਵੇ ਲਈ)",
    aadhaarPlaceholder: "1234",
    phoneLabel: "ਮੋਬਾਈਲ ਨੰਬਰ (ਵਟਸਐਪ ਰੀਮਾਈਂਡਰ ਲਈ)",
    phonePlaceholder: "10-ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ",

    // Dashboard
    dashboardTitle: "ਕਿਸਾਨਸਾਥੀ ਡੈਸ਼ਬੋਰਡ",
    riskForecast: "ਜੋਖਮ ਪੂਰਵ-ਅਨੁਮਾਨ",
    overallRisk: "ਕੁੱਲ ਜੋਖਮ",
    riskScore: "ਜੋਖਮ ਸਕੋਰ",
    topThreats: "ਮੁੱਖ ਖ਼ਤਰੇ",
    sowingAdvice: "ਬਿਜਾਈ ਅਤੇ ਖੇਤੀਬਾੜੀ ਸਲਾਹ",
    recommendedInsurance: "ਸਿਫਾਰਸ਼ੀ ਬੀਮਾ ਪਾਲਿਸੀ",
    activePolicy: "ਸਰਗਰਮ ਪਾਲਿਸੀ ਕਵਰੇਜ",
    enrolledStatus: "ਦਰਜ ਅਤੇ ਸਰਗਰਮ",
    premiumPaid: "ਪ੍ਰੀਮੀਅਮ ਭੁਗਤਾਨ",
    sumInsured: "ਬੀਮਾ ਰਾਸ਼ੀ",
    changePolicy: "ਪਾਲਿਸੀ ਬਦਲੋ",
    activeClaims: "ਸਰਗਰਮ ਦਾਅਵਿਆਂ ਦੀ ਸਥਿਤੀ",
    noClaims: "ਅਜੇ ਤੱਕ ਕੋਈ ਦਾਅਵਾ ਦਰਜ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।",
    seeAllOptions: "ਸਾਰੇ ਵਿਕਲਪ ਦੇਖੋ",
    followUp: "ਫਾਲੋ-ਅੱਪ ਕਰੋ",
    remaining: "ਬਾਕੀ",
    days: "ਦਿਨ",
    hours: "ਘੰਟੇ",
    minutes: "ਮਿੰਟ",
    seconds: "ਸਕਿੰਟ",
    weatherForecastTitle: "14-ਦਿਨਾਂ ਦਾ ਮੌਸਮ ਪੂਰਵ-ਅਨੁਮਾਨ",
    tempMax: "ਵੱਧ ਤੋਂ ਵੱਧ ਤਾਪਮਾਨ (°C)",
    precip: "ਮੀਂਹ (mm)",

    // Voice Chat
    voiceAgent: "ਕਿਸਾਨਸਾਥੀ ਆਵਾਜ਼ ਸਹਾਇਕ",
    speakNow: "ਹੁਣ ਬੋਲੋ...",
    tapMic: "ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ...",
    processing: "ਪ੍ਰੋਸੈਸਿੰਗ...",
    voiceSupportError: "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਆਵਾਜ਼ ਪਛਾਣ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ। ਲਿਖ ਕੇ ਜਵਾਬ ਦਿਓ।",
    typePlaceholder: "ਆਪਣਾ ਸਵਾਲ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਲਿਖੋ...",
    startClaimButton: "ਨੁਕਸਾਨ ਦਾ ਦਾਅਵਾ ਦਰਜ ਕਰੋ 🌾",
    seePoliciesButton: "ਬੀਮਾ ਪਾਲਿਸੀਆਂ ਦੇਖੋ 📋",

    // Policy Advisor
    policyAdvisorTitle: "ਫਸਲ ਬੀਮਾ ਸਲਾਹਕਾਰ",
    premium: "ਪ੍ਰੀਮੀਅਮ (ਕਿਸ਼ਤ)",
    coverage: "ਬੀਮਾ ਕਵਰੇਜ",
    claimSpeed: "ਦਾਅਵੇ ਦਾ ਨਿਪਟਾਰਾ",
    bestFor: "ਇਸ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ",
    applyNow: "ਹੁਣੇ ਅਪਲਾਈ ਕਰੋ",
    howToApply: "ਅਪਲਾਈ ਕਿਵੇਂ ਕਰਨਾ ਹੈ",
    recommendedBadge: "ਤੁਹਾਡੇ ਲਈ ਸਰਵੋਤਮ",
    estPremium: "ਅਨੁਮਾਨਿਤ ਪ੍ਰੀਮੀਅਮ",
    estCoverage: "ਅਨੁਮਾਨਿਤ ਕਵਰੇਜ",
    acreVal: "ਪ੍ਰਤੀ ਏਕੜ ਮੁੱਲ",

    // Claim Filing
    fileClaimTitle: "ਫਸਲ ਦੇ ਨੁਕਸਾਨ ਦਾ ਦਾਅਵਾ ਦਰਜ ਕਰੋ",
    claimStep1: "ਨੁਕਸਾਨ ਦੀ ਰਿਪੋਰਟ",
    claimStep2: "ਫੋਟੋ ਦੀ ਜਾਂਚ",
    claimStep3: "ਕਿਸਾਨ ਦੇ ਵੇਰਵੇ",
    claimStep4: "ਸਮੀਖਿਆ ਅਤੇ ਜਮ੍ਹਾਂ ਕਰੋ",
    damageCropLabel: "ਕਿਹੜੀ ਫਸਲ ਦਾ ਨੁਕਸਾਨ ਹੋਇਆ ਹੈ?",
    damageDateLabel: "ਨੁਕਸਾਨ ਕਦੋਂ ਹੋਇਆ?",
    damageTypeLabel: "ਨੁਕਸਾਨ ਕਿਸ ਕਿਸਮ ਦਾ ਹੈ?",
    acresAffectedLabel: "ਕਿੰਨੇ ਏਕੜ ਪ੍ਰਭਾਵਿਤ ਹੋਏ ਹਨ?",
    photoLabel: "ਨੁਕਸਾਨ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ (ਵਿਕਲਪਿਕ)",
    photoAnalyzing: "ਜੈਮਿਨੀ AI ਫੋਟੋ ਦੀ ਜਾਂਚ ਕਰ ਰਿਹਾ ਹੈ...",
    photoSuccess: "ਜਾਂਚ ਪੂਰੀ ਹੋਈ!",
    bankAccountLabel: "ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ",
    ifscLabel: "IFSC ਕੋਡ",
    insPolicyLabel: "ਆਪਣੀ ਬੀਮਾ ਪਾਲਿਸੀ ਚੁਣੋ",
    reviewHeading: "ਜਮ੍ਹਾਂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਜਾਣਕਾਰੀ ਦੀ ਜਾਂਚ ਕਰੋ",
    fileClaimBtn: "ਦਾਅਵਾ ਦਰਜ ਕਰੋ",
    claimSuccessTitle: "ਦਾਅਵਾ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋ ਗਿਆ!",
    claimSuccessMsg: "ਤੁਹਾਡਾ ਦਾਅਵਾ ਦਰਜ ਹੋ ਗਿਆ ਹੈ। ਜੇਕਰ 48 ਘੰਟਿਆਂ ਵਿੱਚ ਕੋਈ ਅਪਡੇਟ ਨਹੀਂ ਮਿਲਦਾ, ਤਾਂ ਅਸੀਂ ਤੁਹਾਨੂੰ ਯਾਦ ਦਿਵਾਵਾਂਗੇ।",
    claimIdText: "ਦਾਅਵਾ ਆਈ.ਡੀ. (Claim ID)",
    deadlineText: "72-ਘੰਟੇ ਦੀ ਆਖਰੀ ਮਿਆਦ",

    // Claim Tracker
    trackerTitle: "ਦਾਅਵਾ ਟਰੈਕਰ",
    claimId: "ਦਾਅਵਾ ਆਈ.ਡੀ.",
    dateFiled: "ਦਰਜ ਕਰਨ ਦੀ ਮਿਤੀ",
    statusFiled: "ਦਰਜ ਕੀਤਾ ਗਿਆ",
    statusVerified: "ਜਾਂਚਿਆ ਗਿਆ",
    statusUnderReview: "ਸਮੀਖਿਆ ਅਧੀਨ",
    statusApproved: "ਮਨਜ਼ੂਰ",
    statusPaid: "ਮੁਆਵਜ਼ਾ ਦਿੱਤਾ ਗਿਆ",
    viewDetails: "ਵੇਰਵੇ ਦੇਖੋ",
    hideDetails: "ਵੇਰਵੇ ਛੁਪਾਓ",

    // Enrollment Wizard
    enrollTitle: "ਡਿਜੀਟਲ ਬੀਮਾ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    enrollStep1: "ਆਧਾਰ ਕਾਰਡ ਸਕੈਨ ਕਰੋ",
    enrollStep2: "ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਸਕੈਨ ਕਰੋ",
    enrollStep3: "ਪਾਲਿਸੀ ਦੀ ਸਿਫਾਰਸ਼",
    enrollStep4: "ਪੀਡੀਐਫ ਤਿਆਰ ਕਰੋ",
    scanAadhaarLabel: "ਆਧਾਰ ਕਾਰਡ ਦੀ ਫੋਟੋ",
    scanLandLabel: "ਜ਼ਮੀਨੀ ਦਸਤਾਵੇਜ਼ ਦੀ ਫੋਟੋ",
    scanAadhaarDesc: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਆਧਾਰ ਕਾਰਡ ਦੀ ਸਾਫ਼ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ। ਏਆਈ ਤੁਹਾਡੇ ਵੇਰਵੇ ਆਪਣੇ ਆਪ ਕੱਢ ਲਵੇਗਾ।",
    scanLandDesc: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ / ਜਮ੍ਹਾਬੰਦੀ ਦਸਤਾਵੇਜ਼ ਦੀ ਸਾਫ਼ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ।",
    looksGood: "ਕੀ ਇਹ ਵੇਰਵੇ ਸਹੀ ਹਨ?",
    confirmBtn: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ",
    retakeBtn: "ਦੁਬਾਰਾ ਅੱਪਲੋਡ ਕਰੋ",
    recommendationTitle: "ਤੁਹਾਡੇ ਲਈ ਖਾਸ ਬੀਮਾ ਸਿਫ਼ਾਰਸ਼",
    generatePDFBtn: "ਐਪਲੀਕੇਸ਼ਨ PDF ਤਿਆਰ ਕਰੋ",
    downloadPDFBtn: "ਐਪਲੀਕੇਸ਼ਨ PDF ਡਾਊਨਲੋਡ ਕਰੋ",
    whatsappShareBtn: "ਵਟਸਐਪ 'ਤੇ ਸਾਂਝਾ ਕਰੋ",
    successAppTitle: "ਬੀਮਾ ਅਰਜ਼ੀ ਤਿਆਰ ਹੈ!",
    successAppMsg: "ਤੁਹਾਡੀ ਬੀਮਾ ਅਰਜ਼ੀ ਦੀ PDF ਸਫ਼ਲਤਾਪੂਰਵਕ ਤਿਆਰ ਹੋ ਗਈ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਇਸਨੂੰ ਪ੍ਰਿੰਟ ਕਰੋ ਅਤੇ ਆਪਣੇ ਨੇੜਲੇ ਕਾਮਨ ਸਰਵਿਸ ਸੈਂਟਰ (CSC) ਵਿਖੇ ਜਮ੍ਹਾਂ ਕਰੋ।",
    mismatchWarning: "ਚੇਤਾਵਨੀ: ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਵਿਚਲਾ ਨਾਮ ਆਧਾਰ ਕਾਰਡ ਦੇ ਨਾਮ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ! ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰੋ।",
    extractedDetails: "ਏਆਈ ਦੁਆਰਾ ਕੱਢੇ ਗਏ ਵੇਰਵੇ",
    confidenceLabel: "ਏਆਈ ਦਾ ਭਰੋਸਾ ਪੱਧਰ",
    dobLabel: "ਜਨਮ ਮਿਤੀ",
    acresLabel: "ਕੁੱਲ ਏਕੜ",
    landTypeLabel: "ਜ਼ਮੀਨ ਦੀ ਕਿਸਮ"
  },
  hi: {
    appName: "किसानसाथी",
    tagline: "एक काम करो, बाकी सब किसानसाथी करेगा",
    punjabiTagline: "ਇੱਕ ਕੰਮ ਕਰੋ, ਬਾਕੀ ਸਭ ਕਿਸਾਨ ਸਾਥੀ ਕਰੇਗਾ",
    statBar: "10% किसानों के पास बीमा है · ₹1500Cr फसल नुकसान में तबाह · 72 घंटे की दावा खिड़की जो ज्यादातर किसान चूक जाते हैं",
    startInLanguage: "पंजाबी में शुरू करें",
    selectLanguage: "भाषा चुनें",
    next: "आगे",
    back: "पीछे",
    submit: "जमा करें",
    complete: "सेटअप पूरा करें",
    loading: "लोड हो रहा है...",

    // Onboarding
    onboardTitle: "किसान प्रोफाइल सेटअप",
    step: "चरण",
    nameLabel: "आपका नाम क्या है?",
    namePlaceholder: "अपना पूरा नाम दर्ज करें",
    districtLabel: "आपका खेत किस जिले में है?",
    districtSelect: "जिला चुनें",
    landLabel: "आपकी भूमि का आकार कितना है (एकड़ में)?",
    landPlaceholder: "एकड़",
    landHectares: "हेक्टेयर में बराबर",
    primaryCropLabel: "आपकी मुख्य फसल कौन सी है?",
    secondaryCropLabel: "आपकी दूसरी फसल कौन सी है? (वैकल्पिक)",
    secondaryCropNone: "कोई नहीं",
    cropSelect: "फसल चुनें",
    insuranceLabel: "क्या आपके पास वर्तमान में फसल बीमा है?",
    insuranceYes: "हाँ, मेरे पास बीमा है",
    insuranceNo: "नहीं, मेरे पास नहीं है",
    insuranceUnsure: "पता नहीं",
    aadhaarLabel: "आधार कार्ड (अंतिम 4 अंक - दावा प्री-फिल के लिए)",
    aadhaarPlaceholder: "1234",
    phoneLabel: "मोबाइल नंबर (व्हाट्सएप रिमाइंडर के लिए)",
    phonePlaceholder: "10-अंकों का मोबाइल नंबर",

    // Dashboard
    dashboardTitle: "किसानसाथी डैशबोर्ड",
    riskForecast: "जोखिम पूर्वानुमान",
    overallRisk: "कुल जोखिम",
    riskScore: "जोखिम स्कोर",
    topThreats: "प्रमुख खतरे",
    sowingAdvice: "बुवाई और कृषि सलाह",
    recommendedInsurance: "अनुशंसित बीमा पॉलिसी",
    activePolicy: "सक्रिय पॉलिसी कवरेज",
    enrolledStatus: "नामांकित और सक्रिय",
    premiumPaid: "प्रीमियम भुगतान",
    sumInsured: "बीमा राशि",
    changePolicy: "पॉलिसी बदलें",
    activeClaims: "सक्रिय दावों की स्थिति",
    noClaims: "अभी तक कोई दावा दर्ज नहीं किया गया है।",
    seeAllOptions: "सभी विकल्प देखें",
    followUp: "फॉलो-अप करें",
    remaining: "शेष",
    days: "दिन",
    hours: "घंटे",
    minutes: "मिनट",
    seconds: "सेकंड",
    weatherForecastTitle: "14-दिवसीय मौसम पूर्वानुमान",
    tempMax: "अधिकतम तापमान (°C)",
    precip: "बारिश (mm)",

    // Voice Chat
    voiceAgent: "किसानसाथी आवाज सहायक",
    speakNow: "अब बोलें...",
    tapMic: "बोलने के लिए माइक दबाएं",
    listening: "सुन रहा है...",
    processing: "प्रसंस्करण...",
    voiceSupportError: "इस ब्राउज़र में आवाज पहचान समर्थित नहीं है। लिखकर जवाब दें।",
    typePlaceholder: "अपना सवाल अपनी भाषा में लिखें...",
    startClaimButton: "दावा दर्ज करना शुरू करें 🌾",
    seePoliciesButton: "बीमा विकल्प देखें 📋",

    // Policy Advisor
    policyAdvisorTitle: "फसल बीमा सलाहकार",
    premium: "प्रीमियम (किश्त)",
    coverage: "बीमा कवरेज",
    claimSpeed: "दावा निपटान",
    bestFor: "इसके लिए सर्वोत्तम",
    applyNow: "अभी नामांकन करें",
    howToApply: "आवेदन कैसे करें",
    recommendedBadge: "आपके लिए सर्वोत्तम",
    estPremium: "अनुमानित प्रीमियम",
    estCoverage: "अनुमानित कवरेज",
    acreVal: "प्रति एकड़ मूल्य",

    // Claim Filing
    fileClaimTitle: "फसल क्षति का दावा दर्ज करें",
    claimStep1: "क्षति रिपोर्ट",
    claimStep2: "फोटो सत्यापन",
    claimStep3: "किसान का विवरण",
    claimStep4: "समीक्षा और सबमिट करें",
    damageCropLabel: "कौन सी फसल क्षतिग्रस्त हुई है?",
    damageDateLabel: "क्षति कब हुई?",
    damageTypeLabel: "नुकसान किस प्रकार का है?",
    acresAffectedLabel: "कितने एकड़ प्रभावित हैं?",
    photoLabel: "क्षति की फोटो अपलोड करें (वैकल्पिक)",
    photoAnalyzing: "जेमिनी AI फोटो का विश्लेषण कर रहा है...",
    photoSuccess: "विश्लेषण पूरा हुआ!",
    bankAccountLabel: "बैंक खाता संख्या",
    ifscLabel: "IFSC कोड",
    insPolicyLabel: "अपनी बीमा पॉलिसी चुनें",
    reviewHeading: "जमा करने से पहले जानकारी सत्यापित करें",
    fileClaimBtn: "दावा दर्ज करें",
    claimSuccessTitle: "दावा सफलतापूर्वक दर्ज किया गया!",
    claimSuccessMsg: "आपका दावा दर्ज कर लिया गया है। यदि 48 घंटों में कोई अपडेट नहीं मिलता है, तो हम आपको याद दिलाएंगे।",
    claimIdText: "दावा आईडी (Claim ID)",
    deadlineText: "72-घंटे की समय सीमा",

    // Claim Tracker
    trackerTitle: "दावा ट्रैकर",
    claimId: "दावा आईडी",
    dateFiled: "दर्ज करने की तिथि",
    statusFiled: "दर्ज किया गया",
    statusVerified: "सत्यापित",
    statusUnderReview: "समीक्षाधीन",
    statusApproved: "स्वीकृत",
    statusPaid: "मुआवजा वितरित",
    viewDetails: "विवरण देखें",
    hideDetails: "विवरण छुपाएं",

    // Enrollment Wizard
    enrollTitle: "डिजिटल नामांकन",
    enrollStep1: "आधार कार्ड स्कैन करें",
    enrollStep2: "भूमि रिकॉर्ड स्कैन करें",
    enrollStep3: "पॉलिसी की सिफारिश",
    enrollStep4: "पीडीएफ बनाएं",
    scanAadhaarLabel: "आधार कार्ड की फोटो",
    scanLandLabel: "भूमि दस्तावेज की फोटो",
    scanAadhaarDesc: "कृपया अपने आधार कार्ड की साफ फोटो अपलोड करें। एआई विवरण स्वतः ही निकाल लेगा।",
    scanLandDesc: "कृपया अपने भूमि रिकॉर्ड / जमाबंदी दस्तावेज की साफ फोटो अपलोड करें।",
    looksGood: "क्या यह विवरण सही है?",
    confirmBtn: "पुष्टि करें और आगे बढ़ें",
    retakeBtn: "पुनः अपलोड करें",
    recommendationTitle: "आपके लिए अनुशंसित बीमा पॉलिसी",
    generatePDFBtn: "आवेदन PDF उत्पन्न करें",
    downloadPDFBtn: "आवेदन PDF डाउनलोड करें",
    whatsappShareBtn: "व्हाट्सएप पर साझा करें",
    successAppTitle: "आवेदन सफलतापूर्वक तैयार!",
    successAppMsg: "आपकी बीमा आवेदन पीडीएफ सफलतापूर्वक तैयार हो गई है। कृपया इसे प्रिंट करें और अपने निकटतम कॉमन सर्विस सेंटर (CSC) में जमा करें।",
    mismatchWarning: "चेतावनी: भूमि रिकॉर्ड में नाम आधार कार्ड के नाम से मेल नहीं खाता है! कृपया दोबारा जांचें।",
    extractedDetails: "एआई द्वारा निकाले गए विवरण",
    confidenceLabel: "एआई विश्वास स्तर",
    dobLabel: "जन्म तिथि",
    acresLabel: "कुल एकड़",
    landTypeLabel: "भूमि का प्रकार"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLangState] = useState(() => {
    return localStorage.getItem('kisan_lang') || 'pa';
  });

  const setLanguage = (lang) => {
    setLangState(lang);
    localStorage.setItem('kisan_lang', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
